name: flutter_dice_3d
description: 3D Dice (Flutter Web) mit MVVM, Three + Physik
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gl: ^0.0.21
  three_dart: ^0.0.1
  vector_math: ^2.1.4
  js: ^0.6.7
  web: ^0.5.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/textures/dice_uv.png
